# Generated by Django 4.1.3 on 2022-11-24 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='users_favlist',
            field=models.ManyToManyField(blank=True, related_name='users_tvfav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='users_watchedlist',
            field=models.ManyToManyField(blank=True, related_name='users_tvwatchedlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_tvwishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
